name: CICD

on:
  workflow_dispatch: # Enables manual trigger
    inputs:
        environment:
          description: 'Select the environment to deploy'
          required: true
          type: choice
          options:
            - development
            - test
        branch:
          description: 'Enter the branch to deploy from'
          required: true
jobs:
  validate-branch:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'  # Only run on workflow_dispatch
    steps:
      - uses : actions/checkout@v3
      - name: Check if branch exists
        run: |
          if git ls-remote --heads origin refs/heads/${{ github.event.inputs.branch }} | grep -q "${{ github.event.inputs.branch }}"; then
            echo "Branch '${{ github.event.inputs.branch }}' exists. Proceeding..."
          else
            echo "Error: Branch '${{ github.event.inputs.branch }}' does not exist in the repository."
            exit 1
          fi
  check:
    runs-on: ubuntu-latest
    needs: validate-branch
    if: github.event_name != 'workflow_dispatch' || success()
    steps:
        - name : Check job 2 
          run :
             echo "Job 2 running"
